### ISSUE TITLE
deliverystatus would not be restricted to failing cases

### ISSUE THREAD

**Issue by hatukanezumi** [sisimai/p5-Sisimai#155]
Documentation on deliverystatus of Sisimai::Data says that "The range of values only 4.x.x or 5.x.x".  Why this restriction is imposed?  I personally examine if Sisimai can be used as bounce processing engine of Sympa mailing list manager in the future.  Its bounce management and message tracking features have to detect successful, 2.x.x notifications also.

Sisimai::Dataではdeliverystatusを4.x.xか5.x.xに制限しているようですが、なにか理由があるのでしょうか。将来的にSympaのバウンス処理エンジンにSisimaiを使えたらいいな、と思い個人的に調べているのですが、Sympaのバウンス処理やメッセージ追跡機能では成功 (2.x.x) の通知も処理できなければなりません。

cf. <https://www.sympa.org/manual/bounces>.

**Comment by azumakuniyuki** [comment]
書くのが楽なので日本語だけで失礼します。

理由は僕自身が4.X.X, 5.X.Xだけあれば良いというもので`Status: 2.X.X`なものは意図的に除外しています。https://github.com/sisimai/p5-Sisimai/blob/master/lib/Sisimai/Data.pm#L171

しかしながら、2.X.Xである解析結果が「あると困る」わけでもないので、絶対に実装しないということはありません。実装するとすれば、"reason: success"か"reason: delivered"のような感じになると思います。ただ、手元に開発用サンプルとしてあるメール数万通の中に`Status: 2.X.X`になっているメールが殆どないので、もしもそのようなメールをたくさんお持ちであれば、https://github.com/sisimai/p5-Sisimai/tree/master/set-of-emails/to-be-debugged-because/sisimai-cannot-parse-yet に適当な名前で何通か入れてPull-Requestを投げてください。

**Comment by azumakuniyuki** [comment]
Method option might be implemented. The option is for skipping parsed record which reason is "delivered".
```perl
Sisimai->make('/path/to/mbox', { 'error_only' => 1 });
```

**Comment by azumakuniyuki** [comment]
Following code shows example to get parsed data which reason is "delivered".
```perl
Sisimai->make('/path/to/mbox', 'delivered' => 1);
```
