### ISSUE TITLE
Web API option

### ISSUE THREAD

**Issue by beeing** [sisimai/p5-Sisimai#337]
Hi, is there option or any project that is using Sisimai to wrap into a web api?

Instead of reading from mbox, can pass in email content from HTTP API.

Thanks.

**Comment by azumakuniyuki** [comment]
@beeing Hello, We have no plan to implement web related features on Sisimai because Sisimai is just a bounce mail parser library. However, beginning from v4.23.0, Sisimai can read a bounce mail from a variable (need to not read from a file). If you create a script for reading bounce mail data from HTTP using the feature, you can read and parse a mailbox via HTTP.

Thanks.

**Comment by beeing** [comment]
Noted, thanks for the tip!
